language: android
jdk: oraclejdk8
sudo: false
addons:
  apt:
    packages:
    - lynx
android:
  components:
  - platform-tools
  - tools
  - build-tools-25.0.2
  - android-25
  - extra-android-m2repository
before_install: chmod +x gradle/buildWithTravis.sh
script: 
  - gradle/buildWithTravis.sh
  - gnag-build.sh
after_failure: lynx -dump app/build/outputs/gnag/gnag.html
env:
  global:
  - secure: TZ11ozcJozynKr37pRPY2METtIEsDav//mE7wiCEumM4W59QMMnVqjJGTxBipbAuAX36PnEg0/jZbHfXjVJ4py9tGIDB3nlDULqRN/0Ddko/y4gzPQLVpvD22UU0N6g/r0tTJ4H775nxWF07Jw4nohtit7GVZS9Z/dgYvSFE7r2blnflzBBqqRZ2godE0r+8oZV6bRqpo/XxLEqiaBJS7cNbfZIKb+EnwPPuslA4ZdqPAM6U8rV43rzP4oi0M0Z+33s8D/ppDNhU6fPtt8cLIpJaMR5hLowg/U1y919Gp6wpA75Ttx9wZuxBFeAyJxKhJ0O5Myt21Soyw4blayUqqba3i/Nh+voNogwa9JUWzG/AOPDRQqCqKG0yswoRiKfTprSS6w487E1mHpLygftkaTAYKU3HYE/MZl8VYw6FUBC3QSNL5IJ/K8+k5K+Q9xwRBh9W57sclDcAq4fchrH4SKnYQ4GwFpLzyZBblL02ya+wi1kFxLlyHHPZNV/ZLAFG5uc/q1xfs3G6IPcjaRDWk2Ole0vTfqoCV1BVGKJ4+/M4XC+A6ML09CyOYzyu0mZFqWBzyCN3k3Up9sP+ysA9Et28ZO2JbCass3EV8hn1kF4eGwLgOtRpklZCttwLYPqmMjZQeFevF5+QRSZC80eHjf7kxQDwdBMja+dQS3xrIyE=
  - secure: LPWlPox2p8IiKQ8McuuK9e5jkuizp5A2m1nRjyGaq0FYyZD0rQ/AipiE6J25uyemxw11ZyJwno5pdrqytTQxDP2M4hVxMKU5vqvjVrVPDkSfTc0/xjW6efA+F2TBMzQavwANgS4y0OkKe18yZMPva/5sW9JbAuhbVDZn+rjRgoc7BSjX/xqw1QFmAmQXAfNxaUxpBmXSQbiZX67bFem9C77Ymhcd4bwvVu67ukVEQ+BhJw94y95j7enUBA9ioMQN8LIMH+/2U+YwHgQKaBYDQ1Y4PTxfOD8lis7z9m5ODXjCIEINJ2DXv4LM91oGtffQDftX+7P8J8oOF+p5AQWH85xgQh4bsuvRDJo0KXrUkTZ5knx76t+po9pxuLes3Mt0ykqAs5orpMBFPB6xYM7GWmzrGdIIHa4QdwmQyu8DyLCbRn3uCaIsEmxu6t+QOlEG9fEqog+TrRoPoM9ExzXQ9hyDAAqjhEVemhaqv5u8jjNtsV6s2MZyBEdH/BMbKEx9eBCsGCi5k++FPnIWB8ekUSsN8NUZvUXLZ3+7nEvLHjRBBonlJGuVuRjYpsOoCcaDvN3BVfDjA7+Ps7Y7Ci8SitzTYC/YLPNBp91oCjX7kDG13nOFgSiWZaUBrdekB5ush4TPxf4UOZuPHjadFin+c03iFn3cWKJo+Fd/66OLPV0=

